---
title: "Quarto document with python and R"
execute: 
  echo: true
  warning: false
output:
  quarto::quarto_document:
    kernel: python
---

## Introduction

This document is an example of how I can use python and R within the same quarto document and publish to the web.

```{r}
library(reticulate)
use_python("C:/ProgramData/anaconda3")
library(tidyverse)
library(plotly)
library(htmlwidgets)
```

## Python code chunk

```{python}
import pandas as pd

# Creating business counts dataframe
df = pd.read_csv('https://www.nomisweb.co.uk/api/v01/dataset/NM_141_1.data.csv?geography=1853882369...1853882372,1853882374...1853882377,1853882380...1853882382&date=latest&industry=150994945...150994965&employment_sizeband=0&legal_status=0&measures=20100')
df = df[['GEOGRAPHY_CODE', 'GEOGRAPHY_NAME', 'INDUSTRY_NAME', 'INDUSTRY_CODE', 'OBS_VALUE']]
df = df.rename(columns = {'GEOGRAPHY_CODE' : 'Code', 'GEOGRAPHY_NAME' : 'Area', 'INDUSTRY_NAME' : 'Sector', 'INDUSTRY_CODE' : 'Sector_code', 'OBS_VALUE': 'Number'})

```

## R code chunk

```{r}
r_df = py$df

p <- ggplot(data = r_df, aes(y = Area, x = Number, fill = Sector_code)) + 
  geom_col()

ggplotly(p)
```


